name: Copybara PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
    paths-ignore:
      - '.github/**'

  workflow_dispatch:
    inputs:
      status:
        description: PR migration status
        required: true
        type: string
      pr_number:
        description: PR number
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.repository == 'stepankuzmin/copybara-dst' && github.event_name == 'pull_request_target'
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'stepankuzmin',
              repo: 'copybara-sot',
              workflow_id: 'project-copybara-pr.yml',
              ref: 'main',
              inputs: {
                pr_number: '${{ github.event.pull_request.number }}'
              }
            });

  receive:
    runs-on: ubuntu-latest
    if: github.repository == 'stepankuzmin/copybara-dst' && github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: 'stepankuzmin',
              repo: 'copybara-dst',
              pull_number: ${{ inputs.pr_number }}
            });

            await github.rest.checks.create({
              owner: 'stepankuzmin',
              repo: 'copybara-dst',
              name: 'Copybara Migration',
              head_sha: pr.data.head.sha,
              status: 'completed',
              conclusion: '${{ inputs.status }}',
              completed_at: new Date().toISOString()
            });
