name: Copybara PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
    paths-ignore:
      - '.github/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.repository == 'stepankuzmin/copybara-dst'
    steps:
      - name: Trigger Copybara workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            console.log('mergeable_state', pr.data.mergeable_state);

            await github.rest.actions.createWorkflowDispatch({
              owner: 'stepankuzmin',
              repo: 'copybara-sot',
              workflow_id: 'project-copybara-pr.yml',
              ref: 'main',
              inputs: {
                pr_number: '${{ github.event.pull_request.number }}',
                mergeable_state: pr.data.mergeable_state
              }
            });
