name: Copybara PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.repository == 'stepankuzmin/copybara-dst'
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'stepankuzmin',
              repo: 'copybara-sot',
              event_type: 'project_copybara_pr',
              client_payload: { number: "${{ github.event.pull_request.number }}" }
            })
