name: Dispatch

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/stepankuzmin/copybara-sot/dispatches \
            -d '{"event_type": "pull_request_target", "client_payload": {"number": "${{ github.event.pull_request.number }}"}}'
