name: PR notify

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
    paths-ignore:
      - '.github/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.repository == 'stepankuzmin/copybara-dst'
    steps:
      - name: Notify upstream
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'stepankuzmin',
              repo: 'copybara-sot',
              workflow_id: 'import-public-pr.yml',
              ref: 'main',
              inputs: {
                pr_number: '${{ github.event.pull_request.number }}'
              }
            });
