name: Mirror to public

on:
  push:
    paths:
      - "project/**"
      - "!project/copy.bara.sky"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            project
            .github/actions/copybara

      - name: Mirror to public repository
        uses: ./.github/actions/copybara
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          run: migrate project/copy.bara.sky push
