name: Mirror to public

on:
  push:
    paths:
      - "project/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            project
            .github/actions/copybara

      - name: Mirror to public repository
        uses: ./.github/actions/copybara
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          run: migrate copy.bara.sky push --ignore-noop
