name: Copybara Push

on:
  push:
    paths:
      - "project/**"
      - "!project/copy.bara.sky"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Copybara needs full history

      - name: Push
        if: github.ref_name == github.event.repository.default_branch
        uses: ./.github/actions/copybara
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          run: migrate project/copy.bara.sky push
