name: Copybara PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number in the public repo
        required: true
        type: string

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Copybara needs full history

      - name: Migrate PR from public repo
        id: copybara
        uses: ./.github/actions/copybara
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          run: migrate project/copy.bara.sky pr ${{ inputs.pr_number }}

      - uses: actions/github-script@v7
        if: always()
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: 'stepankuzmin',
              repo: 'copybara-dst',
              pull_number: ${{ inputs.pr_number }}
            });

            const green = '${{ steps.copybara.outcome }}' === 'success';

            await github.rest.repos.createCommitStatus({
              owner: 'stepankuzmin',
              repo: 'copybara-dst',
              sha: pr.data.head.sha,
              state: green ? 'success' : 'failure',
              context: 'Copybara PR / sync',
              description: green ? 'Successful' : 'Failed',
              target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            });
