name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - "project/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mirror-check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ./project
            ./.github/actions/copybara
      - uses: actions/github-script@v7
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        with:
          script: |
            if (!/<public>.*<\/public>/.test(${{env.PR_BODY}})) {
              core.setFailed('PR body must contain a `<public>commit message</public>`');
            }
      - name: Validate PR migration to public repo
        uses: ./.github/actions/copybara
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        with:
          run: migrate copy.bara.sky push ${{ github.ref }} --force-message "$PR_BODY" --squash --dry-run

  check:
    runs-on: ubuntu-latest
    if: github.event.action != 'edited'
    defaults:
      run:
        working-directory: project
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ./project
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: project/package-lock.json
      - run: npm ci --no-audit --no-fund
      - run: npm run tsc
      - run: npm test
