name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - "project/**"
      - "copy.bara.sky"
      - ".github/actions/copybara/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mirror-check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ./project
            ./.github/actions/copybara
      - name: Check public commit message
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          if [[ ! "$PR_BODY" =~ \<public\>.*\</public\> ]]; then
            echo "::error::PR body must contain <public>commit message</public>"
            exit 1
          fi
      - name: Validate PR migration to public repo
        uses: ./.github/actions/copybara
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        with:
          run: migrate copy.bara.sky push ${{ github.head_ref }} --force-message "$PR_BODY" --squash --ignore-noop --dry-run

  check:
    runs-on: ubuntu-latest
    if: github.event.action != 'edited'
    defaults:
      run:
        working-directory: project
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ./project
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: project/package-lock.json
      - run: npm ci --no-audit --no-fund
      - run: npm run tsc
      - run: npm test
