name: Copybara PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number in the public repo
        required: true
        type: string

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Copybara needs full history

      - name: Setup Copybara
        uses: ./.github/actions/setup-copybara

      - name: Set up Git credentials
        run: |
          git config --global credential.helper store
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          echo "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Copybara PR
        id: copybara
        run: |
          java -jar copybara.jar migrate project/copy.bara.sky pr ${{ inputs.pr_number }}

      - uses: actions/github-script@v7
        if: always()
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: 'stepankuzmin',
              repo: 'copybara-dst',
              pull_number: ${{ inputs.pr_number }}
            });

            const green = '${{ steps.copybara.outcome }}' === 'success';

            await github.rest.repos.createCommitStatus({
              owner: 'stepankuzmin',
              repo: 'copybara-dst',
              sha: pr.data.head.sha,
              state: green ? 'success' : 'failure',
              context: 'Copybara PR / sync',
              description: green ? 'Successful' : 'Failed',
            });
